/*
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// import { AccessibilityBridge, AccessibilityEventsDelegate } from "@ohos/flutter_ohos";
import { describe, expect, it } from "@ohos/hypium";

export default function AccessibilityEventsDelegateUnitTest() {
  // describe('AccessibilityEventsDelegate', () => {
  //   it("AccessibilityEventsDelegate_requestSendAccessibilityEvent", 0, requestSendAccessibilityEvent);
  //
  //   it("AccessibilityEventsDelegate_onAccessibilityHoverEvent", 0, onAccessibilityHoverEvent);
  // })
}

// function requestSendAccessibilityEvent() {
//   let delegate = new AccessibilityEventsDelegate();
//   let result = delegate.requestSendAccessibilityEvent(new AccessibilityBridge());
//   expect(result).assertTrue();
// }
//
// function onAccessibilityHoverEvent() {
//   let delegate = new AccessibilityEventsDelegate();
//   let result = delegate.onAccessibilityHoverEvent(new AccessibilityBridge());
//   expect(result).assertTrue();
// }