/*
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ApiLevel {
  static API_11: number = 11;
  static API_12: number = 12;
  static API_13: number = 13;
  static API_14: number = 14;
  static API_15: number = 15;
  static API_16: number = 16;
  static API_17: number = 17;
  static API_18: number = 18;
  static API_19: number = 19;
  static API_20: number = 20;
}